// imports.gen.c — GERADO por new-port-arm.sh para 'sonic4ep1' (libs3e_android.so)
// 151 imports. Resolução: fallback dlsym + src/imports.c (shims).
#include "imports.h"
#include "so_util.h"
#include <stdio.h>

FILE *stderr_fake;
DynLibFunction dynlib_functions[] = {
    {"__sonic4ep1_dummy__", 0}, /* sentinela; resolução real = dlsym+imports.c */
};
size_t dynlib_numfunctions = sizeof(dynlib_functions)/sizeof(dynlib_functions[0]);

// ============ referência: imports por categoria (do recon) ============
//   liblog  __android_log_write
//   cxx  __cxa_atexit
//   cxx  __cxa_finalize
//   pass  __errno
//   abi  __gnu_Unwind_Find_exidx
//   UNKNOWN  __google_potentially_blocking_region_begin
//   UNKNOWN  __google_potentially_blocking_region_end
//   UNKNOWN  __sF
//   pass  abort
//   pass  accept
//   pass  access
//   UNKNOWN  arc4random
//   pass  atoi
//   pass  bind
//   UNKNOWN  bsd_signal
//   UNKNOWN  chmod
//   UNKNOWN  clock_getres
//   pass  clock_gettime
//   pass  close
//   pass  closedir
//   pass  connect
//   UNKNOWN  daylight
//   UNKNOWN  dlclose
//   UNKNOWN  dlerror
//   UNKNOWN  dlopen
//   UNKNOWN  dlsym
//   pass  exit
//   pass  fclose
//   pass  fcntl
//   pass  fgets
//   pass  fopen
//   pass  fprintf
//   pass  fputc
//   pass  fputs
//   pass  fread
//   pass  free
//   UNKNOWN  freeaddrinfo
//   UNKNOWN  fscanf
//   pass  fseek
//   pass  ftell
//   UNKNOWN  ftruncate
//   pass  fwrite
//   UNKNOWN  getaddrinfo
//   pass  getenv
//   UNKNOWN  gethostname
//   UNKNOWN  getpeername
//   pass  getpid
//   pass  getsockname
//   pass  getsockopt
//   pass  gettimeofday
//   UNKNOWN  gmtime_r
//   pass  inet_aton
//   pass  inet_ntoa
//   pass  inet_ntop
//   pass  inet_pton
//   pass  inflate
//   pass  inflateEnd
//   pass  inflateInit2_
//   pass  inflateInit_
//   UNKNOWN  isxdigit
//   pass  listen
//   UNKNOWN  localtime_r
//   UNKNOWN  longjmp
//   pass  lrand48
//   pass  lseek
//   pass  malloc
//   pass  memcmp
//   pass  memcpy
//   pass  memmove
//   pass  memset
//   pass  mkdir
//   pass  mktime
//   pass  mmap
//   pass  mprotect
//   pass  munmap
//   UNKNOWN  nice
//   pass  open
//   pass  opendir
//   pthread  pthread_attr_init
//   pthread  pthread_attr_setstack
//   pthread  pthread_attr_setstacksize
//   pthread  pthread_cond_broadcast
//   pthread  pthread_cond_destroy
//   pthread  pthread_cond_init
//   pthread  pthread_cond_timedwait
//   pthread  pthread_cond_wait
//   pthread  pthread_create
//   pthread  pthread_equal
//   pthread  pthread_exit
//   pthread  pthread_getspecific
//   pthread  pthread_join
//   pthread  pthread_key_create
//   pthread  pthread_key_delete
//   pthread  pthread_mutex_destroy
//   pthread  pthread_mutex_init
//   pthread  pthread_mutex_lock
//   pthread  pthread_mutex_trylock
//   pthread  pthread_mutex_unlock
//   pthread  pthread_once
//   pthread  pthread_self
//   pthread  pthread_setspecific
//   UNKNOWN  raise
//   pass  read
//   pass  readdir
//   pass  realloc
//   pass  recv
//   pass  recvfrom
//   UNKNOWN  remove
//   pass  rename
//   pass  rmdir
//   pass  select
//   pass  send
//   pass  sendto
//   UNKNOWN  setjmp
//   pass  setlocale
//   pass  setsockopt
//   UNKNOWN  sigaction
//   pass  snprintf
//   pass  socket
//   pass  sprintf
//   pass  srand48
//   pass  sscanf
//   pass  stat
//   UNKNOWN  statfs
//   pass  strcasecmp
//   pass  strcat
//   pass  strchr
//   pass  strcmp
//   pass  strcpy
//   pass  strdup
//   pass  strerror
//   pass  strlen
//   pass  strncat
//   pass  strncmp
//   pass  strncpy
//   pass  strrchr
//   pass  strstr
//   pass  strtod
//   pass  strtok
//   pass  strtol
//   pass  time
//   UNKNOWN  tmpfile
//   pass  tolower
//   UNKNOWN  tzname
//   UNKNOWN  tzset
//   UNKNOWN  uname
//   pass  unlink
//   pass  usleep
//   UNKNOWN  valloc
//   pass  vsnprintf
//   pass  write
