// imports.gen.c — GERADO por new-port-arm.sh para 'tasm2' (libtasm2.so)
// 396 imports. Resolução: fallback dlsym + src/imports.c (shims).
#include "imports.h"
#include "so_util.h"
#include <stdio.h>

FILE *stderr_fake;
DynLibFunction dynlib_functions[] = {
    {"__tasm2_dummy__", 0}, /* sentinela; resolução real = dlsym+imports.c */
};
size_t dynlib_numfunctions = sizeof(dynlib_functions)/sizeof(dynlib_functions[0]);

// ============ referência: imports por categoria (do recon) ============
//   android  ALooper_forThread
//   android  ALooper_prepare
//   android  ASensorEventQueue_disableSensor
//   android  ASensorEventQueue_enableSensor
//   android  ASensorEventQueue_getEvents
//   android  ASensorEventQueue_setEventRate
//   android  ASensorManager_createEventQueue
//   android  ASensorManager_getDefaultSensor
//   android  ASensorManager_getInstance
//   opensles  SL_IID_BUFFERQUEUE
//   opensles  SL_IID_ENGINE
//   opensles  SL_IID_PLAY
//   abi  __aeabi_atexit
//   liblog  __android_log_print
//   liblog  __android_log_vprint
//   UNKNOWN  __assert2
//   pass  __errno
//   abi  __gnu_Unwind_Find_exidx
//   UNKNOWN  __page_size
//   UNKNOWN  __sF
//   abi  __stack_chk_fail
//   abi  __stack_chk_guard
//   UNKNOWN  _ctype_
//   UNKNOWN  _tolower_tab_
//   pass  _toupper_tab_
//   pass  abort
//   pass  accept
//   pass  access
//   pass  acos
//   UNKNOWN  acosf
//   UNKNOWN  asctime
//   pass  asin
//   UNKNOWN  asinf
//   pass  atan
//   pass  atan2
//   pass  atan2f
//   UNKNOWN  atanf
//   pass  atoi
//   pass  atol
//   pass  bind
//   UNKNOWN  bsd_signal
//   pass  bsearch
//   UNKNOWN  btowc
//   pass  calloc
//   pass  ceil
//   pass  ceilf
//   pass  chdir
//   UNKNOWN  chmod
//   UNKNOWN  clearerr
//   UNKNOWN  clock
//   pass  clock_gettime
//   pass  close
//   pass  closedir
//   pass  connect
//   pass  cos
//   pass  cosf
//   UNKNOWN  difftime
//   UNKNOWN  dlclose
//   UNKNOWN  dlerror
//   UNKNOWN  dlopen
//   UNKNOWN  dlsym
//   UNKNOWN  epoll_create
//   UNKNOWN  epoll_ctl
//   UNKNOWN  epoll_wait
//   pass  exit
//   pass  exp
//   pass  expf
//   pass  fclose
//   pass  fcntl
//   pass  fdopen
//   pass  fflush
//   pass  fgets
//   pass  floor
//   pass  floorf
//   pass  fmod
//   pass  fmodf
//   pass  fopen
//   pass  fprintf
//   pass  fputc
//   pass  fputs
//   pass  fread
//   pass  free
//   UNKNOWN  freeaddrinfo
//   pass  fseek
//   UNKNOWN  fseeko
//   pass  fstat
//   pass  ftell
//   UNKNOWN  ftello
//   pass  fwrite
//   UNKNOWN  getaddrinfo
//   pass  getc
//   pass  getcwd
//   UNKNOWN  getegid
//   pass  getenv
//   UNKNOWN  geteuid
//   UNKNOWN  getgid
//   pass  gethostbyname
//   UNKNOWN  gethostname
//   UNKNOWN  getpeername
//   pass  getpid
//   UNKNOWN  getpwuid
//   pass  getsockname
//   pass  getsockopt
//   pass  gettimeofday
//   UNKNOWN  getuid
//   UNKNOWN  getwc
//   gles  glActiveTexture
//   gles  glAttachShader
//   gles  glBindBuffer
//   gles  glBindFramebuffer
//   gles  glBindRenderbuffer
//   gles  glBindTexture
//   gles  glBlendColor
//   gles  glBlendEquation
//   gles  glBlendEquationSeparate
//   gles  glBlendFunc
//   gles  glBlendFuncSeparate
//   gles  glBufferData
//   gles  glBufferSubData
//   gles  glCheckFramebufferStatus
//   gles  glClear
//   gles  glClearColor
//   gles  glClearDepthf
//   gles  glClearStencil
//   gles  glColorMask
//   gles  glCompileShader
//   gles  glCompressedTexImage2D
//   gles  glCompressedTexImage3DOES
//   gles  glCompressedTexSubImage2D
//   gles  glCompressedTexSubImage3DOES
//   gles  glCopyTexSubImage2D
//   gles  glCreateProgram
//   gles  glCreateShader
//   gles  glCullFace
//   gles  glDeleteBuffers
//   gles  glDeleteFencesNV
//   gles  glDeleteFramebuffers
//   gles  glDeleteProgram
//   gles  glDeleteRenderbuffers
//   gles  glDeleteShader
//   gles  glDeleteTextures
//   gles  glDepthFunc
//   gles  glDepthMask
//   gles  glDepthRangef
//   gles  glDisable
//   gles  glDisableVertexAttribArray
//   gles  glDrawArrays
//   gles  glDrawElements
//   gles  glEnable
//   gles  glEnableVertexAttribArray
//   gles  glFinish
//   gles  glFinishFenceNV
//   gles  glFlush
//   gles  glFramebufferRenderbuffer
//   gles  glFramebufferTexture2D
//   gles  glFrontFace
//   gles  glGenBuffers
//   gles  glGenFencesNV
//   gles  glGenFramebuffers
//   gles  glGenRenderbuffers
//   gles  glGenTextures
//   gles  glGenerateMipmap
//   gles  glGetActiveAttrib
//   gles  glGetActiveUniform
//   gles  glGetAttribLocation
//   gles  glGetError
//   gles  glGetFloatv
//   gles  glGetIntegerv
//   gles  glGetProgramInfoLog
//   gles  glGetProgramiv
//   gles  glGetShaderInfoLog
//   gles  glGetShaderSource
//   gles  glGetShaderiv
//   gles  glGetString
//   gles  glGetUniformLocation
//   gles  glLineWidth
//   gles  glLinkProgram
//   gles  glMapBufferOES
//   gles  glPixelStorei
//   gles  glPolygonOffset
//   gles  glReadPixels
//   gles  glRenderbufferStorage
//   gles  glSampleCoverage
//   gles  glScissor
//   gles  glSetFenceNV
//   gles  glShaderSource
//   gles  glStencilFunc
//   gles  glStencilMask
//   gles  glStencilOp
//   gles  glTestFenceNV
//   gles  glTexImage2D
//   gles  glTexImage3DOES
//   gles  glTexParameterf
//   gles  glTexParameteri
//   gles  glTexSubImage2D
//   gles  glTexSubImage3DOES
//   gles  glUniform1f
//   gles  glUniform1fv
//   gles  glUniform1i
//   gles  glUniform1iv
//   gles  glUniform2fv
//   gles  glUniform2iv
//   gles  glUniform3fv
//   gles  glUniform3iv
//   gles  glUniform4fv
//   gles  glUniform4iv
//   gles  glUniformMatrix2fv
//   gles  glUniformMatrix3fv
//   gles  glUniformMatrix4fv
//   gles  glUnmapBufferOES
//   gles  glUseProgram
//   gles  glVertexAttrib4f
//   gles  glVertexAttribPointer
//   gles  glViewport
//   pass  gmtime
//   UNKNOWN  gmtime_r
//   pass  inet_addr
//   pass  inet_ntoa
//   pass  ioctl
//   pass  isalnum
//   pass  isalpha
//   pass  isupper
//   UNKNOWN  iswctype
//   UNKNOWN  isxdigit
//   pass  ldexp
//   pass  listen
//   pass  localtime
//   UNKNOWN  localtime_r
//   pass  log
//   pass  log10
//   pass  logf
//   UNKNOWN  longjmp
//   pass  lrand48
//   pass  lseek
//   pass  malloc
//   UNKNOWN  mbrtowc
//   UNKNOWN  mbstowcs
//   pass  memchr
//   pass  memcmp
//   pass  memcpy
//   UNKNOWN  memmem
//   pass  memmove
//   pass  memset
//   pass  mkdir
//   UNKNOWN  mkstemp
//   pass  mktime
//   pass  mmap
//   UNKNOWN  modff
//   UNKNOWN  mremap
//   pass  munmap
//   pass  nanosleep
//   pass  open
//   pass  opendir
//   pass  perror
//   pass  pipe
//   pass  poll
//   pass  pow
//   pass  powf
//   UNKNOWN  pread
//   pass  printf
//   pthread  pthread_attr_destroy
//   pthread  pthread_attr_getdetachstate
//   pthread  pthread_attr_init
//   pthread  pthread_attr_setdetachstate
//   pthread  pthread_attr_setstacksize
//   pthread  pthread_cond_broadcast
//   pthread  pthread_cond_destroy
//   pthread  pthread_cond_init
//   pthread  pthread_cond_signal
//   pthread  pthread_cond_timedwait
//   pthread  pthread_cond_wait
//   pthread  pthread_create
//   pthread  pthread_detach
//   pthread  pthread_equal
//   pthread  pthread_getschedparam
//   pthread  pthread_getspecific
//   pthread  pthread_join
//   pthread  pthread_key_create
//   pthread  pthread_key_delete
//   pthread  pthread_mutex_destroy
//   pthread  pthread_mutex_init
//   pthread  pthread_mutex_lock
//   pthread  pthread_mutex_trylock
//   pthread  pthread_mutex_unlock
//   pthread  pthread_mutexattr_destroy
//   pthread  pthread_mutexattr_init
//   pthread  pthread_mutexattr_settype
//   pthread  pthread_once
//   pthread  pthread_self
//   pthread  pthread_setschedparam
//   pthread  pthread_setspecific
//   pass  putc
//   UNKNOWN  putchar
//   pass  puts
//   UNKNOWN  putwc
//   pass  qsort
//   UNKNOWN  raise
//   pass  read
//   pass  readdir
//   pass  realloc
//   pass  recv
//   pass  recvfrom
//   pass  recvmsg
//   UNKNOWN  remove
//   pass  rename
//   pass  rmdir
//   pass  sched_get_priority_max
//   pass  sched_get_priority_min
//   pass  sched_yield
//   pass  select
//   pthread  sem_destroy
//   pthread  sem_init
//   pthread  sem_post
//   pthread  sem_trywait
//   pthread  sem_wait
//   pass  send
//   UNKNOWN  sendfile
//   pass  sendmsg
//   pass  sendto
//   UNKNOWN  setjmp
//   pass  setlocale
//   pass  setsockopt
//   pass  setvbuf
//   pass  shutdown
//   UNKNOWN  sigaction
//   pass  sin
//   pass  sinf
//   UNKNOWN  sinh
//   opensles  slCreateEngine
//   pass  snprintf
//   pass  socket
//   pass  sprintf
//   pass  srand48
//   pass  sscanf
//   pass  stat
//   UNKNOWN  statfs
//   pass  strcasecmp
//   pass  strcat
//   pass  strchr
//   pass  strcmp
//   pass  strcoll
//   pass  strcpy
//   UNKNOWN  strcspn
//   pass  strdup
//   pass  strerror
//   UNKNOWN  strerror_r
//   pass  strftime
//   pass  strlen
//   pass  strncasecmp
//   pass  strncmp
//   pass  strncpy
//   UNKNOWN  strpbrk
//   UNKNOWN  strptime
//   pass  strrchr
//   pass  strstr
//   pass  strtod
//   pass  strtok
//   UNKNOWN  strtok_r
//   pass  strtol
//   UNKNOWN  strtoll
//   pass  strtoul
//   UNKNOWN  strxfrm
//   UNKNOWN  swprintf
//   UNKNOWN  syscall
//   pass  sysconf
//   pass  tan
//   pass  tanf
//   pass  time
//   UNKNOWN  times
//   pass  tolower
//   UNKNOWN  towlower
//   UNKNOWN  towupper
//   UNKNOWN  umask
//   UNKNOWN  ungetc
//   UNKNOWN  ungetwc
//   pass  unlink
//   pass  usleep
//   UNKNOWN  vfprintf
//   pass  vsnprintf
//   pass  vsprintf
//   UNKNOWN  wcrtomb
//   UNKNOWN  wcscmp
//   UNKNOWN  wcscoll
//   UNKNOWN  wcscpy
//   UNKNOWN  wcsftime
//   UNKNOWN  wcslen
//   UNKNOWN  wcsxfrm
//   UNKNOWN  wctob
//   UNKNOWN  wctype
//   UNKNOWN  wmemchr
//   UNKNOWN  wmemcmp
//   UNKNOWN  wmemcpy
//   UNKNOWN  wmemmove
//   UNKNOWN  wmemset
//   pass  write
//   UNKNOWN  writev
