// imports.gen.c — GERADO por new-port-arm.sh para 'bfbc2' (libbc2.so)
// 165 imports. Resolução: fallback dlsym + src/imports.c (shims).
#include "imports.h"
#include "so_util.h"
#include <stdio.h>

FILE *stderr_fake;
DynLibFunction dynlib_functions[] = {
    {"__bfbc2_dummy__", 0}, /* sentinela; resolução real = dlsym+imports.c */
};
size_t dynlib_numfunctions = sizeof(dynlib_functions)/sizeof(dynlib_functions[0]);

// ============ referência: imports por categoria (do recon) ============
//   pass  abort
//   pass  accept
//   pass  acos
//   abi  __aeabi_atexit
//   abi  __aeabi_d2ulz
//   abi  __aeabi_f2iz
//   abi  __aeabi_f2ulz
//   abi  __aeabi_idiv
//   abi  __aeabi_idivmod
//   abi  __aeabi_l2d
//   abi  __aeabi_l2f
//   abi  __aeabi_ldivmod
//   abi  __aeabi_uidiv
//   abi  __aeabi_uidivmod
//   abi  __aeabi_uldivmod
//   abi  __aeabi_unwind_cpp_pr0
//   abi  __aeabi_unwind_cpp_pr1
//   liblog  __android_log_print
//   pass  asin
//   pass  atan
//   pass  atan2
//   pass  atoi
//   pass  bind
//   pass  ceil
//   pass  chdir
//   pass  close
//   pass  closedir
//   pass  connect
//   pass  cos
//   cxx  __cxa_guard_acquire
//   cxx  __cxa_guard_release
//   cxx  __cxa_pure_virtual
//   UNKNOWN  __dso_handle
//   pass  __errno
//   pass  fclose
//   pass  fcntl
//   pass  fflush
//   pass  fgets
//   pass  fileno
//   pass  floor
//   pass  fmod
//   pass  fopen
//   pass  fprintf
//   pass  fread
//   pass  free
//   pass  fseek
//   pass  fstat
//   pass  ftell
//   pass  fwrite
//   UNKNOWN  gai_strerror
//   UNKNOWN  getaddrinfo
//   pass  getcwd
//   pass  gethostbyname
//   UNKNOWN  gethostname
//   UNKNOWN  getnameinfo
//   pass  getpid
//   pass  getsockname
//   pass  gettimeofday
//   gles  glActiveTexture
//   gles  glAlphaFunc
//   gles  glBindBuffer
//   gles  glBindFramebufferOES
//   gles  glBindTexture
//   gles  glBlendFunc
//   gles  glClear
//   gles  glClearColor
//   gles  glClearDepthf
//   gles  glClearStencil
//   gles  glClientActiveTexture
//   gles  glColorMask
//   gles  glColorPointer
//   gles  glCompressedTexImage2D
//   gles  glCullFace
//   gles  glDeleteBuffers
//   gles  glDeleteTextures
//   gles  glDepthFunc
//   gles  glDepthMask
//   gles  glDepthRangef
//   gles  glDisable
//   gles  glDisableClientState
//   gles  glDrawArrays
//   gles  glDrawElements
//   gles  glEnable
//   gles  glEnableClientState
//   gles  glFogf
//   gles  glFogfv
//   gles  glFrontFace
//   gles  glGenTextures
//   gles  glGetError
//   gles  glGetIntegerv
//   gles  glGetString
//   gles  glLoadIdentity
//   gles  glLoadMatrixf
//   gles  glMatrixMode
//   gles  glNormalPointer
//   gles  glReadPixels
//   gles  glScissor
//   gles  glStencilFunc
//   gles  glStencilOp
//   gles  glTexCoordPointer
//   gles  glTexEnvf
//   gles  glTexEnvfv
//   gles  glTexImage2D
//   gles  glTexParameteri
//   gles  glVertexPointer
//   gles  glViewport
//   pass  inet_ntoa
//   pass  ioctl
//   pass  ldexp
//   pass  listen
//   pass  localtime
//   pass  log
//   pass  lrand48
//   pass  lstat
//   pass  malloc
//   pass  memcmp
//   pass  memcpy
//   pass  memmove
//   pass  memset
//   pass  mkdir
//   pass  opendir
//   pass  pow
//   pass  printf
//   pass  readdir
//   pass  realloc
//   pass  recv
//   pass  recvfrom
//   pass  rmdir
//   pass  select
//   pass  send
//   pass  sendto
//   UNKNOWN  __sF
//   pass  shutdown
//   UNKNOWN  sigaction
//   pass  sin
//   pass  snprintf
//   pass  socket
//   pass  sqrt
//   pass  sscanf
//   abi  __stack_chk_fail
//   abi  __stack_chk_guard
//   pass  strcat
//   pass  strchr
//   pass  strcmp
//   pass  strcpy
//   pass  strerror
//   pass  strlen
//   pass  strncat
//   pass  strncmp
//   pass  strncpy
//   pass  strrchr
//   pass  strstr
//   UNKNOWN  strtoll
//   UNKNOWN  system
//   pass  tan
//   pass  time
//   pass  tolower
//   pass  toupper
//   pass  unlink
//   UNKNOWN  _Unwind_Backtrace
//   UNKNOWN  _Unwind_VRS_Get
//   pass  vsnprintf
//   cxx  _ZdlPv
//   cxx  _Znaj
//   cxx  _Znwj
