// imports.gen.c — GERADO por new-port-arm.sh para 'deadspace' (libDeadSpace.so)
// 398 imports. Resolução: fallback dlsym + src/imports.c (shims).
#include "imports.h"
#include "so_util.h"
#include <stdio.h>

FILE *stderr_fake;
DynLibFunction dynlib_functions[] = {
    {"__deadspace_dummy__", 0}, /* sentinela; resolução real = dlsym+imports.c */
};
size_t dynlib_numfunctions = sizeof(dynlib_functions)/sizeof(dynlib_functions[0]);

// ============ referência: imports por categoria (do recon) ============
//   UNKNOWN  _Z17androidGetTmpRootv
//   UNKNOWN  _Z22androidGetExternalRootv
//   abi  __aeabi_atexit
//   liblog  __android_log_print
//   liblog  __android_log_vprint
//   liblog  __android_log_write
//   UNKNOWN  __atomic_cmpxchg
//   UNKNOWN  __atomic_dec
//   UNKNOWN  __atomic_inc
//   UNKNOWN  __atomic_swap
//   cxx  __cxa_begin_cleanup
//   cxx  __cxa_call_unexpected
//   cxx  __cxa_guard_acquire
//   cxx  __cxa_guard_release
//   cxx  __cxa_pure_virtual
//   cxx  __cxa_type_match
//   UNKNOWN  __dso_handle
//   pass  __errno
//   abi  __gnu_Unwind_Find_exidx
//   UNKNOWN  __isinf
//   UNKNOWN  __page_size
//   UNKNOWN  __sF
//   abi  __stack_chk_fail
//   abi  __stack_chk_guard
//   UNKNOWN  _ctype_
//   UNKNOWN  _tolower_tab_
//   pass  _toupper_tab_
//   pass  abort
//   pass  accept
//   pass  acos
//   UNKNOWN  acosf
//   UNKNOWN  asinf
//   pass  atan
//   pass  atan2
//   pass  atan2f
//   pass  atoi
//   pass  bind
//   pass  calloc
//   pass  ceil
//   pass  ceilf
//   pass  chdir
//   UNKNOWN  chmod
//   UNKNOWN  clock
//   pass  clock_gettime
//   pass  close
//   pass  closedir
//   pass  connect
//   pass  cos
//   pass  cosf
//   UNKNOWN  execv
//   pass  exit
//   pass  exp
//   pass  expf
//   pass  fclose
//   pass  fcntl
//   pass  fflush
//   pass  fgetc
//   pass  fgets
//   pass  floor
//   pass  floorf
//   pass  fmodf
//   pass  fopen
//   UNKNOWN  fork
//   pass  fprintf
//   pass  fputs
//   pass  fread
//   pass  free
//   UNKNOWN  freeaddrinfo
//   pass  fseek
//   pass  fstat
//   UNKNOWN  fsync
//   pass  ftell
//   UNKNOWN  ftruncate
//   UNKNOWN  fwide
//   pass  fwrite
//   UNKNOWN  getaddrinfo
//   pass  getcwd
//   pass  getenv
//   UNKNOWN  getpeername
//   pass  getsockname
//   pass  getsockopt
//   pass  gettimeofday
//   gles  glActiveTexture
//   gles  glAlphaFunc
//   gles  glAlphaFuncx
//   gles  glBindBuffer
//   gles  glBindFramebufferOES
//   gles  glBindRenderbufferOES
//   gles  glBindTexture
//   gles  glBlendEquationOES
//   gles  glBlendEquationSeparateOES
//   gles  glBlendFunc
//   gles  glBlendFuncSeparateOES
//   gles  glBufferData
//   gles  glBufferSubData
//   gles  glCheckFramebufferStatusOES
//   gles  glClear
//   gles  glClearColor
//   gles  glClearColorx
//   gles  glClearDepthf
//   gles  glClearDepthx
//   gles  glClearStencil
//   gles  glClientActiveTexture
//   gles  glClipPlanef
//   gles  glClipPlanex
//   gles  glColor4f
//   gles  glColor4ub
//   gles  glColor4x
//   gles  glColorMask
//   gles  glColorPointer
//   gles  glCompressedTexImage2D
//   gles  glCompressedTexSubImage2D
//   gles  glCopyTexImage2D
//   gles  glCopyTexSubImage2D
//   gles  glCullFace
//   gles  glCurrentPaletteMatrixOES
//   gles  glDeleteBuffers
//   gles  glDeleteFramebuffersOES
//   gles  glDeleteRenderbuffersOES
//   gles  glDeleteTextures
//   gles  glDepthFunc
//   gles  glDepthMask
//   gles  glDepthRangef
//   gles  glDepthRangex
//   gles  glDisable
//   gles  glDisableClientState
//   gles  glDrawArrays
//   gles  glDrawElements
//   gles  glDrawTexfOES
//   gles  glDrawTexfvOES
//   gles  glDrawTexiOES
//   gles  glDrawTexivOES
//   gles  glDrawTexsOES
//   gles  glDrawTexsvOES
//   gles  glDrawTexxOES
//   gles  glDrawTexxvOES
//   gles  glEGLImageTargetRenderbufferStorageOES
//   gles  glEGLImageTargetTexture2DOES
//   gles  glEnable
//   gles  glEnableClientState
//   gles  glFinish
//   gles  glFlush
//   gles  glFogf
//   gles  glFogfv
//   gles  glFogx
//   gles  glFogxv
//   gles  glFramebufferRenderbufferOES
//   gles  glFramebufferTexture2DOES
//   gles  glFrontFace
//   gles  glFrustumf
//   gles  glFrustumx
//   gles  glGenBuffers
//   gles  glGenFramebuffersOES
//   gles  glGenRenderbuffersOES
//   gles  glGenTextures
//   gles  glGenerateMipmapOES
//   gles  glGetBooleanv
//   gles  glGetBufferParameteriv
//   gles  glGetBufferPointervOES
//   gles  glGetClipPlanef
//   gles  glGetClipPlanex
//   gles  glGetError
//   gles  glGetFixedv
//   gles  glGetFloatv
//   gles  glGetFramebufferAttachmentParameterivOES
//   gles  glGetIntegerv
//   gles  glGetLightfv
//   gles  glGetLightxv
//   gles  glGetMaterialfv
//   gles  glGetMaterialxv
//   gles  glGetPointerv
//   gles  glGetRenderbufferParameterivOES
//   gles  glGetString
//   gles  glGetTexEnvfv
//   gles  glGetTexEnviv
//   gles  glGetTexEnvxv
//   gles  glGetTexGenfvOES
//   gles  glGetTexGenivOES
//   gles  glGetTexGenxvOES
//   gles  glGetTexParameterfv
//   gles  glGetTexParameteriv
//   gles  glGetTexParameterxv
//   gles  glHint
//   gles  glIsBuffer
//   gles  glIsEnabled
//   gles  glIsFramebufferOES
//   gles  glIsRenderbufferOES
//   gles  glIsTexture
//   gles  glLightModelf
//   gles  glLightModelfv
//   gles  glLightModelx
//   gles  glLightModelxv
//   gles  glLightf
//   gles  glLightfv
//   gles  glLightx
//   gles  glLightxv
//   gles  glLineWidth
//   gles  glLineWidthx
//   gles  glLoadIdentity
//   gles  glLoadMatrixf
//   gles  glLoadMatrixx
//   gles  glLoadPaletteFromModelViewMatrixOES
//   gles  glLogicOp
//   gles  glMapBufferOES
//   gles  glMaterialf
//   gles  glMaterialfv
//   gles  glMaterialx
//   gles  glMaterialxv
//   gles  glMatrixIndexPointerOES
//   gles  glMatrixMode
//   gles  glMultMatrixf
//   gles  glMultMatrixx
//   gles  glMultiTexCoord4f
//   gles  glMultiTexCoord4x
//   gles  glNormal3f
//   gles  glNormal3x
//   gles  glNormalPointer
//   gles  glOrthof
//   gles  glOrthox
//   gles  glPixelStorei
//   gles  glPointParameterf
//   gles  glPointParameterfv
//   gles  glPointParameterx
//   gles  glPointParameterxv
//   gles  glPointSize
//   gles  glPointSizePointerOES
//   gles  glPointSizex
//   gles  glPolygonOffset
//   gles  glPolygonOffsetx
//   gles  glPopMatrix
//   gles  glPushMatrix
//   gles  glQueryMatrixxOES
//   gles  glReadPixels
//   gles  glRenderbufferStorageOES
//   gles  glRotatef
//   gles  glRotatex
//   gles  glSampleCoverage
//   gles  glSampleCoveragex
//   gles  glScalef
//   gles  glScalex
//   gles  glScissor
//   gles  glShadeModel
//   gles  glStencilFunc
//   gles  glStencilMask
//   gles  glStencilOp
//   gles  glTexCoordPointer
//   gles  glTexEnvf
//   gles  glTexEnvfv
//   gles  glTexEnvi
//   gles  glTexEnviv
//   gles  glTexEnvx
//   gles  glTexEnvxv
//   gles  glTexGenfOES
//   gles  glTexGenfvOES
//   gles  glTexGeniOES
//   gles  glTexGenivOES
//   gles  glTexGenxOES
//   gles  glTexGenxvOES
//   gles  glTexImage2D
//   gles  glTexParameterf
//   gles  glTexParameterfv
//   gles  glTexParameteri
//   gles  glTexParameteriv
//   gles  glTexParameterx
//   gles  glTexParameterxv
//   gles  glTexSubImage2D
//   gles  glTranslatef
//   gles  glTranslatex
//   gles  glUnmapBufferOES
//   gles  glVertexPointer
//   gles  glViewport
//   gles  glWeightPointerOES
//   pass  gmtime
//   pass  ldexp
//   pass  listen
//   pass  localtime
//   pass  log
//   pass  log10
//   UNKNOWN  log10f
//   pass  logf
//   UNKNOWN  longjmp
//   pass  lrand48
//   pass  lseek
//   pass  malloc
//   pass  memcmp
//   pass  memcpy
//   pass  memmove
//   pass  memset
//   pass  mkdir
//   pass  mktime
//   pass  mmap
//   pass  modf
//   pass  munmap
//   pass  nanosleep
//   pass  open
//   pass  opendir
//   pass  poll
//   pass  pow
//   pass  powf
//   UNKNOWN  prctl
//   pthread  pthread_attr_destroy
//   pthread  pthread_attr_getstack
//   pthread  pthread_attr_init
//   pthread  pthread_attr_setdetachstate
//   pthread  pthread_attr_setschedparam
//   pthread  pthread_attr_setstack
//   pthread  pthread_attr_setstacksize
//   pthread  pthread_cond_broadcast
//   pthread  pthread_cond_destroy
//   pthread  pthread_cond_init
//   pthread  pthread_cond_signal
//   pthread  pthread_cond_timedwait
//   pthread  pthread_cond_wait
//   pthread  pthread_create
//   pthread  pthread_exit
//   pthread  pthread_getattr_np
//   pthread  pthread_getschedparam
//   pthread  pthread_getspecific
//   pthread  pthread_key_create
//   pthread  pthread_key_delete
//   pthread  pthread_mutex_destroy
//   pthread  pthread_mutex_init
//   pthread  pthread_mutex_lock
//   pthread  pthread_mutex_trylock
//   pthread  pthread_mutex_unlock
//   pthread  pthread_mutexattr_destroy
//   pthread  pthread_mutexattr_init
//   pthread  pthread_mutexattr_setpshared
//   pthread  pthread_mutexattr_settype
//   pthread  pthread_once
//   pthread  pthread_self
//   pthread  pthread_setschedparam
//   pthread  pthread_setspecific
//   pass  qsort
//   UNKNOWN  raise
//   pass  read
//   pass  readdir
//   UNKNOWN  readdir_r
//   pass  realloc
//   pass  recv
//   pass  recvfrom
//   UNKNOWN  remove
//   pass  rename
//   pass  rmdir
//   UNKNOWN  sbrk
//   pass  sched_yield
//   pthread  sem_destroy
//   pthread  sem_getvalue
//   pthread  sem_init
//   pthread  sem_post
//   pthread  sem_timedwait
//   pthread  sem_trywait
//   pthread  sem_wait
//   pass  send
//   pass  sendto
//   pass  setenv
//   UNKNOWN  setjmp
//   pass  setsockopt
//   pass  shutdown
//   pass  sin
//   pass  sinf
//   pass  snprintf
//   pass  socket
//   pass  sprintf
//   pass  sqrt
//   pass  sqrtf
//   pass  sscanf
//   pass  stat
//   pass  strcat
//   pass  strchr
//   pass  strcmp
//   pass  strcpy
//   pass  strdup
//   pass  strlen
//   pass  strncmp
//   pass  strncpy
//   pass  strrchr
//   pass  strstr
//   pass  strtod
//   pass  strtok
//   pass  strtol
//   pass  strtoul
//   pass  sysconf
//   UNKNOWN  system
//   pass  tan
//   pass  tanf
//   pass  time
//   UNKNOWN  tzname
//   UNKNOWN  ungetc
//   pass  unlink
//   pass  usleep
//   UNKNOWN  utime
//   pass  vsnprintf
//   pass  vsprintf
//   UNKNOWN  vsscanf
//   UNKNOWN  waitpid
//   UNKNOWN  wcslen
//   pass  write
