// imports_unity.gen.c — GERADO. passthrough via dlsym; resto = stub log.
#include "so_util.h"
#include <stdio.h>
#include <stdint.h>
#include <dlfcn.h>

// stubs (logam nome, 1as 2 vezes, retornam 0)
long stub_ALooper_forThread(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] ALooper_forThread\\n"); return 0; }
long stub_ALooper_prepare(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] ALooper_prepare\\n"); return 0; }
long stub_ANativeWindow_acquire(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] ANativeWindow_acquire\\n"); return 0; }
long stub_ANativeWindow_fromSurface(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] ANativeWindow_fromSurface\\n"); return 0; }
long stub_ANativeWindow_getHeight(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] ANativeWindow_getHeight\\n"); return 0; }
long stub_ANativeWindow_getWidth(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] ANativeWindow_getWidth\\n"); return 0; }
long stub_ANativeWindow_release(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] ANativeWindow_release\\n"); return 0; }
long stub_ANativeWindow_setBuffersGeometry(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] ANativeWindow_setBuffersGeometry\\n"); return 0; }
long stub_ASensorEventQueue_disableSensor(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] ASensorEventQueue_disableSensor\\n"); return 0; }
long stub_ASensorEventQueue_enableSensor(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] ASensorEventQueue_enableSensor\\n"); return 0; }
long stub_ASensorEventQueue_getEvents(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] ASensorEventQueue_getEvents\\n"); return 0; }
long stub_ASensorEventQueue_hasEvents(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] ASensorEventQueue_hasEvents\\n"); return 0; }
long stub_ASensorEventQueue_setEventRate(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] ASensorEventQueue_setEventRate\\n"); return 0; }
long stub_ASensorManager_createEventQueue(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] ASensorManager_createEventQueue\\n"); return 0; }
long stub_ASensorManager_destroyEventQueue(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] ASensorManager_destroyEventQueue\\n"); return 0; }
long stub_ASensorManager_getDefaultSensor(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] ASensorManager_getDefaultSensor\\n"); return 0; }
long stub_ASensorManager_getInstance(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] ASensorManager_getInstance\\n"); return 0; }
long stub_ASensorManager_getSensorList(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] ASensorManager_getSensorList\\n"); return 0; }
long stub_ASensor_getMinDelay(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] ASensor_getMinDelay\\n"); return 0; }
long stub_ASensor_getName(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] ASensor_getName\\n"); return 0; }
long stub_ASensor_getResolution(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] ASensor_getResolution\\n"); return 0; }
long stub_ASensor_getType(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] ASensor_getType\\n"); return 0; }
long stub_ASensor_getVendor(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] ASensor_getVendor\\n"); return 0; }
long stub___android_log_print(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] __android_log_print\\n"); return 0; }
long stub___android_log_vprint(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] __android_log_vprint\\n"); return 0; }
long stub___android_log_write(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] __android_log_write\\n"); return 0; }
long stub___ctype_get_mb_cur_max(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] __ctype_get_mb_cur_max\\n"); return 0; }
long stub___cxa_atexit(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] __cxa_atexit\\n"); return 0; }
long stub___cxa_finalize(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] __cxa_finalize\\n"); return 0; }
long stub___errno(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] __errno\\n"); return 0; }
long stub___google_potentially_blocking_region_begin(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] __google_potentially_blocking_region_begin\\n"); return 0; }
long stub___google_potentially_blocking_region_end(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] __google_potentially_blocking_region_end\\n"); return 0; }
long stub___isnanf(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] __isnanf\\n"); return 0; }
long stub___sF(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] __sF\\n"); return 0; }
long stub___stack_chk_fail(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] __stack_chk_fail\\n"); return 0; }
long stub___stack_chk_guard(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] __stack_chk_guard\\n"); return 0; }
long stub___system_property_get(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] __system_property_get\\n"); return 0; }
long stub__ctype_(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] _ctype_\\n"); return 0; }
long stub_accept(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] accept\\n"); return 0; }
long stub_android_set_abort_message(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] android_set_abort_message\\n"); return 0; }
long stub_asctime(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] asctime\\n"); return 0; }
long stub_bind(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] bind\\n"); return 0; }
long stub_connect(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] connect\\n"); return 0; }
long stub_dl_iterate_phdr(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] dl_iterate_phdr\\n"); return 0; }
long stub_dladdr(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] dladdr\\n"); return 0; }
long stub_environ(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] environ\\n"); return 0; }
long stub_execl(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] execl\\n"); return 0; }
long stub_fork(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] fork\\n"); return 0; }
long stub_freeaddrinfo(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] freeaddrinfo\\n"); return 0; }
long stub_gai_strerror(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] gai_strerror\\n"); return 0; }
long stub_getaddrinfo(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] getaddrinfo\\n"); return 0; }
long stub_gethostbyname(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] gethostbyname\\n"); return 0; }
long stub_gethostname(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] gethostname\\n"); return 0; }
long stub_getnameinfo(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] getnameinfo\\n"); return 0; }
long stub_getpeername(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] getpeername\\n"); return 0; }
long stub_getsockname(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] getsockname\\n"); return 0; }
long stub_getsockopt(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] getsockopt\\n"); return 0; }
long stub_inet_addr(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] inet_addr\\n"); return 0; }
long stub_inet_aton(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] inet_aton\\n"); return 0; }
long stub_inet_ntoa(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] inet_ntoa\\n"); return 0; }
long stub_inet_ntop(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] inet_ntop\\n"); return 0; }
long stub_inet_pton(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] inet_pton\\n"); return 0; }
long stub_kill(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] kill\\n"); return 0; }
long stub_listen(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] listen\\n"); return 0; }
long stub_memalign(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] memalign\\n"); return 0; }
long stub_ptrace(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] ptrace\\n"); return 0; }
long stub_putchar(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] putchar\\n"); return 0; }
long stub_raise(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] raise\\n"); return 0; }
long stub_recv(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] recv\\n"); return 0; }
long stub_recvfrom(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] recvfrom\\n"); return 0; }
long stub_recvmsg(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] recvmsg\\n"); return 0; }
long stub_sched_get_priority_max(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] sched_get_priority_max\\n"); return 0; }
long stub_sched_get_priority_min(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] sched_get_priority_min\\n"); return 0; }
long stub_send(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] send\\n"); return 0; }
long stub_sendmsg(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] sendmsg\\n"); return 0; }
long stub_sendto(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] sendto\\n"); return 0; }
long stub_setsockopt(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] setsockopt\\n"); return 0; }
long stub_shutdown(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] shutdown\\n"); return 0; }
long stub_sigaction(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] sigaction\\n"); return 0; }
long stub_signal(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] signal\\n"); return 0; }
long stub_sigsuspend(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] sigsuspend\\n"); return 0; }
long stub_socket(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] socket\\n"); return 0; }
long stub_strlcpy(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] strlcpy\\n"); return 0; }
long stub_strsep(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] strsep\\n"); return 0; }
long stub_strxfrm(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] strxfrm\\n"); return 0; }
long stub_syscall(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] syscall\\n"); return 0; }
long stub_tcflush(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] tcflush\\n"); return 0; }
long stub_tcgetattr(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] tcgetattr\\n"); return 0; }
long stub_tcsetattr(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] tcsetattr\\n"); return 0; }
long stub_tgkill(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] tgkill\\n"); return 0; }
long stub_waitpid(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] waitpid\\n"); return 0; }
long stub_wcstold(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] wcstold\\n"); return 0; }
long stub_writev(void){ static int n=0; if(n++<2) fprintf(stderr,"[STUB] writev\\n"); return 0; }

// flag: 1 = passthrough (resolver via dlsym), 0 = stub ja setado
static const char *passthrough_names[] = {
  "abort",
  "access",
  "acos",
  "acosf",
  "asin",
  "asinf",
  "atan",
  "atan2",
  "atan2f",
  "atanf",
  "atof",
  "atoi",
  "atol",
  "bsearch",
  "btowc",
  "calloc",
  "chmod",
  "clearerr",
  "clock",
  "clock_getres",
  "clock_gettime",
  "close",
  "closedir",
  "closelog",
  "cos",
  "cosf",
  "difftime",
  "div",
  "dlclose",
  "dlerror",
  "dlopen",
  "dlsym",
  "dup",
  "dup2",
  "eglChooseConfig",
  "eglCreateContext",
  "eglCreatePbufferSurface",
  "eglCreateWindowSurface",
  "eglDestroyContext",
  "eglDestroySurface",
  "eglGetConfigAttrib",
  "eglGetCurrentContext",
  "eglGetCurrentSurface",
  "eglGetDisplay",
  "eglGetError",
  "eglGetProcAddress",
  "eglInitialize",
  "eglMakeCurrent",
  "eglQueryString",
  "eglQuerySurface",
  "eglSwapBuffers",
  "eglSwapInterval",
  "eglTerminate",
  "exit",
  "exp",
  "exp2",
  "exp2f",
  "expf",
  "fabsf",
  "fclose",
  "fcntl",
  "fdopen",
  "feof",
  "ferror",
  "fflush",
  "fgets",
  "fileno",
  "flock",
  "fmod",
  "fmodf",
  "fopen",
  "fprintf",
  "fputc",
  "fputs",
  "fread",
  "free",
  "freelocale",
  "frexp",
  "fscanf",
  "fseek",
  "fstat",
  "ftell",
  "ftruncate",
  "fwrite",
  "getc",
  "getcwd",
  "getenv",
  "getpagesize",
  "getpid",
  "getpriority",
  "getpwuid",
  "gettid",
  "gettimeofday",
  "getuid",
  "gmtime",
  "inflate",
  "inflateEnd",
  "inflateInit2_",
  "ioctl",
  "isalnum",
  "isalpha",
  "isatty",
  "islower",
  "isnan",
  "isspace",
  "isupper",
  "iswalpha",
  "iswblank",
  "iswcntrl",
  "iswctype",
  "iswdigit",
  "iswlower",
  "iswprint",
  "iswpunct",
  "iswspace",
  "iswupper",
  "iswxdigit",
  "isxdigit",
  "ldexp",
  "ldexpf",
  "localeconv",
  "localtime",
  "localtime_r",
  "log",
  "log10",
  "log10f",
  "logf",
  "longjmp",
  "lseek",
  "lseek64",
  "lstat",
  "madvise",
  "malloc",
  "mbrlen",
  "mbrtowc",
  "mbsnrtowcs",
  "mbsrtowcs",
  "mbtowc",
  "memchr",
  "memcmp",
  "memcpy",
  "memmove",
  "memset",
  "mkdir",
  "mktime",
  "mmap",
  "modf",
  "modff",
  "mprotect",
  "munmap",
  "nanosleep",
  "newlocale",
  "open",
  "opendir",
  "openlog",
  "perror",
  "pipe",
  "poll",
  "posix_memalign",
  "pow",
  "powf",
  "prctl",
  "printf",
  "pthread_attr_destroy",
  "pthread_attr_getstack",
  "pthread_attr_init",
  "pthread_attr_setdetachstate",
  "pthread_attr_setstacksize",
  "pthread_cond_broadcast",
  "pthread_cond_destroy",
  "pthread_cond_init",
  "pthread_cond_signal",
  "pthread_cond_timedwait",
  "pthread_cond_wait",
  "pthread_condattr_destroy",
  "pthread_condattr_init",
  "pthread_condattr_setclock",
  "pthread_create",
  "pthread_detach",
  "pthread_equal",
  "pthread_exit",
  "pthread_getattr_np",
  "pthread_getcpuclockid",
  "pthread_getschedparam",
  "pthread_getspecific",
  "pthread_join",
  "pthread_key_create",
  "pthread_key_delete",
  "pthread_kill",
  "pthread_mutex_destroy",
  "pthread_mutex_init",
  "pthread_mutex_lock",
  "pthread_mutex_trylock",
  "pthread_mutex_unlock",
  "pthread_mutexattr_destroy",
  "pthread_mutexattr_init",
  "pthread_mutexattr_settype",
  "pthread_once",
  "pthread_rwlock_destroy",
  "pthread_rwlock_init",
  "pthread_rwlock_rdlock",
  "pthread_rwlock_unlock",
  "pthread_rwlock_wrlock",
  "pthread_self",
  "pthread_setname_np",
  "pthread_setschedparam",
  "pthread_setspecific",
  "puts",
  "qsort",
  "rand",
  "read",
  "readdir",
  "readlink",
  "realloc",
  "realpath",
  "remainder",
  "remove",
  "rename",
  "rmdir",
  "sched_yield",
  "select",
  "sem_destroy",
  "sem_getvalue",
  "sem_init",
  "sem_open",
  "sem_post",
  "sem_timedwait",
  "sem_wait",
  "setenv",
  "setjmp",
  "setlocale",
  "setpriority",
  "setvbuf",
  "sigdelset",
  "sigemptyset",
  "sigfillset",
  "sin",
  "sinf",
  "sleep",
  "snprintf",
  "sprintf",
  "sqrt",
  "sqrtf",
  "srand",
  "sscanf",
  "stat",
  "statfs",
  "strcasecmp",
  "strcat",
  "strchr",
  "strcmp",
  "strcoll",
  "strcpy",
  "strdup",
  "strerror",
  "strerror_r",
  "strftime",
  "strlen",
  "strncat",
  "strncmp",
  "strncpy",
  "strnlen",
  "strpbrk",
  "strrchr",
  "strstr",
  "strtod",
  "strtof",
  "strtok",
  "strtol",
  "strtold",
  "strtold_l",
  "strtoll",
  "strtoll_l",
  "strtoul",
  "strtoull",
  "strtoull_l",
  "swprintf",
  "sysconf",
  "syslog",
  "tan",
  "tanf",
  "time",
  "tolower",
  "toupper",
  "towlower",
  "towupper",
  "truncate",
  "uname",
  "ungetc",
  "unlink",
  "unsetenv",
  "uselocale",
  "usleep",
  "utime",
  "vasprintf",
  "vfprintf",
  "vprintf",
  "vsnprintf",
  "vsprintf",
  "vsscanf",
  "wcrtomb",
  "wcscoll",
  "wcsftime",
  "wcslen",
  "wcsnrtombs",
  "wcstod",
  "wcstof",
  "wcstol",
  "wcstoll",
  "wcstoul",
  "wcstoull",
  "wcsxfrm",
  "wctob",
  "wctype",
  "wmemchr",
  "wmemcmp",
  "wmemcpy",
  "wmemmove",
  "wmemset",
  "write",
  0 };

DynLibFunction dynlib_functions[] = {
  {"ALooper_forThread", (uintptr_t)&stub_ALooper_forThread},
  {"ALooper_prepare", (uintptr_t)&stub_ALooper_prepare},
  {"ANativeWindow_acquire", (uintptr_t)&stub_ANativeWindow_acquire},
  {"ANativeWindow_fromSurface", (uintptr_t)&stub_ANativeWindow_fromSurface},
  {"ANativeWindow_getHeight", (uintptr_t)&stub_ANativeWindow_getHeight},
  {"ANativeWindow_getWidth", (uintptr_t)&stub_ANativeWindow_getWidth},
  {"ANativeWindow_release", (uintptr_t)&stub_ANativeWindow_release},
  {"ANativeWindow_setBuffersGeometry", (uintptr_t)&stub_ANativeWindow_setBuffersGeometry},
  {"ASensorEventQueue_disableSensor", (uintptr_t)&stub_ASensorEventQueue_disableSensor},
  {"ASensorEventQueue_enableSensor", (uintptr_t)&stub_ASensorEventQueue_enableSensor},
  {"ASensorEventQueue_getEvents", (uintptr_t)&stub_ASensorEventQueue_getEvents},
  {"ASensorEventQueue_hasEvents", (uintptr_t)&stub_ASensorEventQueue_hasEvents},
  {"ASensorEventQueue_setEventRate", (uintptr_t)&stub_ASensorEventQueue_setEventRate},
  {"ASensorManager_createEventQueue", (uintptr_t)&stub_ASensorManager_createEventQueue},
  {"ASensorManager_destroyEventQueue", (uintptr_t)&stub_ASensorManager_destroyEventQueue},
  {"ASensorManager_getDefaultSensor", (uintptr_t)&stub_ASensorManager_getDefaultSensor},
  {"ASensorManager_getInstance", (uintptr_t)&stub_ASensorManager_getInstance},
  {"ASensorManager_getSensorList", (uintptr_t)&stub_ASensorManager_getSensorList},
  {"ASensor_getMinDelay", (uintptr_t)&stub_ASensor_getMinDelay},
  {"ASensor_getName", (uintptr_t)&stub_ASensor_getName},
  {"ASensor_getResolution", (uintptr_t)&stub_ASensor_getResolution},
  {"ASensor_getType", (uintptr_t)&stub_ASensor_getType},
  {"ASensor_getVendor", (uintptr_t)&stub_ASensor_getVendor},
  {"__android_log_print", (uintptr_t)&stub___android_log_print},
  {"__android_log_vprint", (uintptr_t)&stub___android_log_vprint},
  {"__android_log_write", (uintptr_t)&stub___android_log_write},
  {"__ctype_get_mb_cur_max", (uintptr_t)&stub___ctype_get_mb_cur_max},
  {"__cxa_atexit", (uintptr_t)&stub___cxa_atexit},
  {"__cxa_finalize", (uintptr_t)&stub___cxa_finalize},
  {"__errno", (uintptr_t)&stub___errno},
  {"__google_potentially_blocking_region_begin", (uintptr_t)&stub___google_potentially_blocking_region_begin},
  {"__google_potentially_blocking_region_end", (uintptr_t)&stub___google_potentially_blocking_region_end},
  {"__isnanf", (uintptr_t)&stub___isnanf},
  {"__sF", (uintptr_t)&stub___sF},
  {"__stack_chk_fail", (uintptr_t)&stub___stack_chk_fail},
  {"__stack_chk_guard", (uintptr_t)&stub___stack_chk_guard},
  {"__system_property_get", (uintptr_t)&stub___system_property_get},
  {"_ctype_", (uintptr_t)&stub__ctype_},
  {"abort", 0},
  {"accept", (uintptr_t)&stub_accept},
  {"access", 0},
  {"acos", 0},
  {"acosf", 0},
  {"android_set_abort_message", (uintptr_t)&stub_android_set_abort_message},
  {"asctime", (uintptr_t)&stub_asctime},
  {"asin", 0},
  {"asinf", 0},
  {"atan", 0},
  {"atan2", 0},
  {"atan2f", 0},
  {"atanf", 0},
  {"atof", 0},
  {"atoi", 0},
  {"atol", 0},
  {"bind", (uintptr_t)&stub_bind},
  {"bsearch", 0},
  {"btowc", 0},
  {"calloc", 0},
  {"chmod", 0},
  {"clearerr", 0},
  {"clock", 0},
  {"clock_getres", 0},
  {"clock_gettime", 0},
  {"close", 0},
  {"closedir", 0},
  {"closelog", 0},
  {"connect", (uintptr_t)&stub_connect},
  {"cos", 0},
  {"cosf", 0},
  {"difftime", 0},
  {"div", 0},
  {"dl_iterate_phdr", (uintptr_t)&stub_dl_iterate_phdr},
  {"dladdr", (uintptr_t)&stub_dladdr},
  {"dlclose", 0},
  {"dlerror", 0},
  {"dlopen", 0},
  {"dlsym", 0},
  {"dup", 0},
  {"dup2", 0},
  {"eglChooseConfig", 0},
  {"eglCreateContext", 0},
  {"eglCreatePbufferSurface", 0},
  {"eglCreateWindowSurface", 0},
  {"eglDestroyContext", 0},
  {"eglDestroySurface", 0},
  {"eglGetConfigAttrib", 0},
  {"eglGetCurrentContext", 0},
  {"eglGetCurrentSurface", 0},
  {"eglGetDisplay", 0},
  {"eglGetError", 0},
  {"eglGetProcAddress", 0},
  {"eglInitialize", 0},
  {"eglMakeCurrent", 0},
  {"eglQueryString", 0},
  {"eglQuerySurface", 0},
  {"eglSwapBuffers", 0},
  {"eglSwapInterval", 0},
  {"eglTerminate", 0},
  {"environ", (uintptr_t)&stub_environ},
  {"execl", (uintptr_t)&stub_execl},
  {"exit", 0},
  {"exp", 0},
  {"exp2", 0},
  {"exp2f", 0},
  {"expf", 0},
  {"fabsf", 0},
  {"fclose", 0},
  {"fcntl", 0},
  {"fdopen", 0},
  {"feof", 0},
  {"ferror", 0},
  {"fflush", 0},
  {"fgets", 0},
  {"fileno", 0},
  {"flock", 0},
  {"fmod", 0},
  {"fmodf", 0},
  {"fopen", 0},
  {"fork", (uintptr_t)&stub_fork},
  {"fprintf", 0},
  {"fputc", 0},
  {"fputs", 0},
  {"fread", 0},
  {"free", 0},
  {"freeaddrinfo", (uintptr_t)&stub_freeaddrinfo},
  {"freelocale", 0},
  {"frexp", 0},
  {"fscanf", 0},
  {"fseek", 0},
  {"fstat", 0},
  {"ftell", 0},
  {"ftruncate", 0},
  {"fwrite", 0},
  {"gai_strerror", (uintptr_t)&stub_gai_strerror},
  {"getaddrinfo", (uintptr_t)&stub_getaddrinfo},
  {"getc", 0},
  {"getcwd", 0},
  {"getenv", 0},
  {"gethostbyname", (uintptr_t)&stub_gethostbyname},
  {"gethostname", (uintptr_t)&stub_gethostname},
  {"getnameinfo", (uintptr_t)&stub_getnameinfo},
  {"getpagesize", 0},
  {"getpeername", (uintptr_t)&stub_getpeername},
  {"getpid", 0},
  {"getpriority", 0},
  {"getpwuid", 0},
  {"getsockname", (uintptr_t)&stub_getsockname},
  {"getsockopt", (uintptr_t)&stub_getsockopt},
  {"gettid", 0},
  {"gettimeofday", 0},
  {"getuid", 0},
  {"gmtime", 0},
  {"inet_addr", (uintptr_t)&stub_inet_addr},
  {"inet_aton", (uintptr_t)&stub_inet_aton},
  {"inet_ntoa", (uintptr_t)&stub_inet_ntoa},
  {"inet_ntop", (uintptr_t)&stub_inet_ntop},
  {"inet_pton", (uintptr_t)&stub_inet_pton},
  {"inflate", 0},
  {"inflateEnd", 0},
  {"inflateInit2_", 0},
  {"ioctl", 0},
  {"isalnum", 0},
  {"isalpha", 0},
  {"isatty", 0},
  {"islower", 0},
  {"isnan", 0},
  {"isspace", 0},
  {"isupper", 0},
  {"iswalpha", 0},
  {"iswblank", 0},
  {"iswcntrl", 0},
  {"iswctype", 0},
  {"iswdigit", 0},
  {"iswlower", 0},
  {"iswprint", 0},
  {"iswpunct", 0},
  {"iswspace", 0},
  {"iswupper", 0},
  {"iswxdigit", 0},
  {"isxdigit", 0},
  {"kill", (uintptr_t)&stub_kill},
  {"ldexp", 0},
  {"ldexpf", 0},
  {"listen", (uintptr_t)&stub_listen},
  {"localeconv", 0},
  {"localtime", 0},
  {"localtime_r", 0},
  {"log", 0},
  {"log10", 0},
  {"log10f", 0},
  {"logf", 0},
  {"longjmp", 0},
  {"lseek", 0},
  {"lseek64", 0},
  {"lstat", 0},
  {"madvise", 0},
  {"malloc", 0},
  {"mbrlen", 0},
  {"mbrtowc", 0},
  {"mbsnrtowcs", 0},
  {"mbsrtowcs", 0},
  {"mbtowc", 0},
  {"memalign", (uintptr_t)&stub_memalign},
  {"memchr", 0},
  {"memcmp", 0},
  {"memcpy", 0},
  {"memmove", 0},
  {"memset", 0},
  {"mkdir", 0},
  {"mktime", 0},
  {"mmap", 0},
  {"modf", 0},
  {"modff", 0},
  {"mprotect", 0},
  {"munmap", 0},
  {"nanosleep", 0},
  {"newlocale", 0},
  {"open", 0},
  {"opendir", 0},
  {"openlog", 0},
  {"perror", 0},
  {"pipe", 0},
  {"poll", 0},
  {"posix_memalign", 0},
  {"pow", 0},
  {"powf", 0},
  {"prctl", 0},
  {"printf", 0},
  {"pthread_attr_destroy", 0},
  {"pthread_attr_getstack", 0},
  {"pthread_attr_init", 0},
  {"pthread_attr_setdetachstate", 0},
  {"pthread_attr_setstacksize", 0},
  {"pthread_cond_broadcast", 0},
  {"pthread_cond_destroy", 0},
  {"pthread_cond_init", 0},
  {"pthread_cond_signal", 0},
  {"pthread_cond_timedwait", 0},
  {"pthread_cond_wait", 0},
  {"pthread_condattr_destroy", 0},
  {"pthread_condattr_init", 0},
  {"pthread_condattr_setclock", 0},
  {"pthread_create", 0},
  {"pthread_detach", 0},
  {"pthread_equal", 0},
  {"pthread_exit", 0},
  {"pthread_getattr_np", 0},
  {"pthread_getcpuclockid", 0},
  {"pthread_getschedparam", 0},
  {"pthread_getspecific", 0},
  {"pthread_join", 0},
  {"pthread_key_create", 0},
  {"pthread_key_delete", 0},
  {"pthread_kill", 0},
  {"pthread_mutex_destroy", 0},
  {"pthread_mutex_init", 0},
  {"pthread_mutex_lock", 0},
  {"pthread_mutex_trylock", 0},
  {"pthread_mutex_unlock", 0},
  {"pthread_mutexattr_destroy", 0},
  {"pthread_mutexattr_init", 0},
  {"pthread_mutexattr_settype", 0},
  {"pthread_once", 0},
  {"pthread_rwlock_destroy", 0},
  {"pthread_rwlock_init", 0},
  {"pthread_rwlock_rdlock", 0},
  {"pthread_rwlock_unlock", 0},
  {"pthread_rwlock_wrlock", 0},
  {"pthread_self", 0},
  {"pthread_setname_np", 0},
  {"pthread_setschedparam", 0},
  {"pthread_setspecific", 0},
  {"ptrace", (uintptr_t)&stub_ptrace},
  {"putchar", (uintptr_t)&stub_putchar},
  {"puts", 0},
  {"qsort", 0},
  {"raise", (uintptr_t)&stub_raise},
  {"rand", 0},
  {"read", 0},
  {"readdir", 0},
  {"readlink", 0},
  {"realloc", 0},
  {"realpath", 0},
  {"recv", (uintptr_t)&stub_recv},
  {"recvfrom", (uintptr_t)&stub_recvfrom},
  {"recvmsg", (uintptr_t)&stub_recvmsg},
  {"remainder", 0},
  {"remove", 0},
  {"rename", 0},
  {"rmdir", 0},
  {"sched_get_priority_max", (uintptr_t)&stub_sched_get_priority_max},
  {"sched_get_priority_min", (uintptr_t)&stub_sched_get_priority_min},
  {"sched_yield", 0},
  {"select", 0},
  {"sem_destroy", 0},
  {"sem_getvalue", 0},
  {"sem_init", 0},
  {"sem_open", 0},
  {"sem_post", 0},
  {"sem_timedwait", 0},
  {"sem_wait", 0},
  {"send", (uintptr_t)&stub_send},
  {"sendmsg", (uintptr_t)&stub_sendmsg},
  {"sendto", (uintptr_t)&stub_sendto},
  {"setenv", 0},
  {"setjmp", 0},
  {"setlocale", 0},
  {"setpriority", 0},
  {"setsockopt", (uintptr_t)&stub_setsockopt},
  {"setvbuf", 0},
  {"shutdown", (uintptr_t)&stub_shutdown},
  {"sigaction", (uintptr_t)&stub_sigaction},
  {"sigdelset", 0},
  {"sigemptyset", 0},
  {"sigfillset", 0},
  {"signal", (uintptr_t)&stub_signal},
  {"sigsuspend", (uintptr_t)&stub_sigsuspend},
  {"sin", 0},
  {"sinf", 0},
  {"sleep", 0},
  {"snprintf", 0},
  {"socket", (uintptr_t)&stub_socket},
  {"sprintf", 0},
  {"sqrt", 0},
  {"sqrtf", 0},
  {"srand", 0},
  {"sscanf", 0},
  {"stat", 0},
  {"statfs", 0},
  {"strcasecmp", 0},
  {"strcat", 0},
  {"strchr", 0},
  {"strcmp", 0},
  {"strcoll", 0},
  {"strcpy", 0},
  {"strdup", 0},
  {"strerror", 0},
  {"strerror_r", 0},
  {"strftime", 0},
  {"strlcpy", (uintptr_t)&stub_strlcpy},
  {"strlen", 0},
  {"strncat", 0},
  {"strncmp", 0},
  {"strncpy", 0},
  {"strnlen", 0},
  {"strpbrk", 0},
  {"strrchr", 0},
  {"strsep", (uintptr_t)&stub_strsep},
  {"strstr", 0},
  {"strtod", 0},
  {"strtof", 0},
  {"strtok", 0},
  {"strtol", 0},
  {"strtold", 0},
  {"strtold_l", 0},
  {"strtoll", 0},
  {"strtoll_l", 0},
  {"strtoul", 0},
  {"strtoull", 0},
  {"strtoull_l", 0},
  {"strxfrm", (uintptr_t)&stub_strxfrm},
  {"swprintf", 0},
  {"syscall", (uintptr_t)&stub_syscall},
  {"sysconf", 0},
  {"syslog", 0},
  {"tan", 0},
  {"tanf", 0},
  {"tcflush", (uintptr_t)&stub_tcflush},
  {"tcgetattr", (uintptr_t)&stub_tcgetattr},
  {"tcsetattr", (uintptr_t)&stub_tcsetattr},
  {"tgkill", (uintptr_t)&stub_tgkill},
  {"time", 0},
  {"tolower", 0},
  {"toupper", 0},
  {"towlower", 0},
  {"towupper", 0},
  {"truncate", 0},
  {"uname", 0},
  {"ungetc", 0},
  {"unlink", 0},
  {"unsetenv", 0},
  {"uselocale", 0},
  {"usleep", 0},
  {"utime", 0},
  {"vasprintf", 0},
  {"vfprintf", 0},
  {"vprintf", 0},
  {"vsnprintf", 0},
  {"vsprintf", 0},
  {"vsscanf", 0},
  {"waitpid", (uintptr_t)&stub_waitpid},
  {"wcrtomb", 0},
  {"wcscoll", 0},
  {"wcsftime", 0},
  {"wcslen", 0},
  {"wcsnrtombs", 0},
  {"wcstod", 0},
  {"wcstof", 0},
  {"wcstol", 0},
  {"wcstold", (uintptr_t)&stub_wcstold},
  {"wcstoll", 0},
  {"wcstoul", 0},
  {"wcstoull", 0},
  {"wcsxfrm", 0},
  {"wctob", 0},
  {"wctype", 0},
  {"wmemchr", 0},
  {"wmemcmp", 0},
  {"wmemcpy", 0},
  {"wmemmove", 0},
  {"wmemset", 0},
  {"write", 0},
  {"writev", (uintptr_t)&stub_writev},
};
size_t dynlib_numfunctions = sizeof(dynlib_functions)/sizeof(dynlib_functions[0]);

// resolve os passthrough via dlsym(RTLD_DEFAULT) em runtime
void recon_fill_passthrough(void){
  for(size_t i=0;i<dynlib_numfunctions;i++){
    if(dynlib_functions[i].func==0){
      void *p = dlsym(RTLD_DEFAULT, dynlib_functions[i].symbol);
      if(p) dynlib_functions[i].func=(uintptr_t)p;
      else fprintf(stderr,"[passthrough FALHOU dlsym] %s\\n", dynlib_functions[i].symbol);
    }
  }
}
